apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  namespace: nexus
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      name: http
      protocol: TCP
  selector:
    app: frontend-app

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frontend-app
  namespace: nexus
spec:
  selector:
    matchLabels:
      app: frontend-app
  serviceName: frontend-app
  podManagementPolicy: Parallel
  replicas: 1
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  
  template:
    metadata:
      labels:
        app: frontend-app
    
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      volumes:
        - name: devcerts
          secret:
            secretName: aspnetapp-cert
      containers:
        - name: frontend-app
          image: afroze9/nexus-frontend-app:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: devcerts
              mountPath: /https/
          env:
            - name: PUBLIC_BASE_URL
              value: https://localhost:7069
            - name: ConsulKV__Url
              value: http://consul.nexus.svc.cluster.local:8500
            - name: ConsulKV__AddGlobalConfig
              value: "true"
            - name: ConsulKV__GlobalConfigKey
              value: "nexus-service/app-config"
            - name: ConsulKV__Key
              value: "company-api/app-config"
            - name: ConsulKV__Token
              valueFrom:
                secretKeyRef:
                  name: company-api-token
                  key: token
            - name: Consul__Host
              value: consul
            - name: GlobalConfiguration.BaseUrl
              value: http://localhost:5032
            - name: ASPNETCORE_URLS
              value: https://+:443;http://+:80
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: dev123
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: /https/aspnetapp.pfx